### ISSUE TITLE
ping not found

### ISSUE THREAD

**Issue by pschuermann** [shoonoise/cabot-docker#11]
Looks like no ping command is installed in the cabot docker image. For the ping checks I get the following error:
````
/bin/sh: 1 : ping: not found
````

**Comment by shoonoise** [comment]
Hi, It seems like base ubuntu docker image does not contain `ping` utility. It's pretty strange, but should fix pretty simple by adding:
`RUN apt-get install ping`  in Dockerfile.
I will see at this issue later.

**Comment by shoonoise** [comment]
@pschuermann I try to reproduce the issue, but I see `ping` command in image.
Please, reopen if you can reproduce this issue again.
