### ISSUE TITLE
django.db.utils.OperationalError: could not connect to server

### ISSUE THREAD

**Issue by greggsoft** [shoonoise/cabot-docker#14]
I found this in end of log of `cabot` container after maestro start:

    django.db.utils.OperationalError: could not connect to server: Connection refused
    	Is the server running on host "127.0.0.1" and accepting
    	TCP/IP connections on port 5432?

**Comment by greggsoft** [comment]
Looks like it's my fail.

I run docker host on virtual host by vagrant. So, I put in `maestro.yml` ip `127.0.0.1` as `vm1` address. And maestro provide this address as host for all services.

**Comment by anutham-b** [comment]
Hi Gregg, Even i am trying to run cabot container on a vagrant host and facing the same problem. What is the IP address that has to be put in the maestro.yml. Any other network configurations to be done on vagrant/maestro ?

**Comment by shoonoise** [comment]
@anutham-b If docker server runs on VM which managed by vagrant, you should use ip from your Vagrantfile (`config.vm.network` line) in `maestro.yml`. I guess.
