### ISSUE TITLE
Deployment with Marathon fails

### ISSUE THREAD

**Issue by tomkp75** [shoonoise/cabot-docker#16]
Hello,

It would be useful to have the SES environment variables (in migrate.sh and run.sh) defaulted to potentially existing environment variables with the same name.
Marathon we can pass env. vars. are currently overridden by the exports in the previously mentionned files.

Also, any reason these exports are in both files ?

Thanks,

Tom

**Comment by shoonoise** [comment]
@tomkp75 Hi! I'm sorry for the late answer.

> any reason these exports are in both files ?

Nope, there is no any reasons. `migrate.sh` was removed.

I [move](https://github.com/shoonoise/cabot-docker/commit/70711c554cbba78e7103bcc838bf5695f8535e8e) some variables to separated env file, but I can't move `SES_HOST` as it should be define before container start.
