### ISSUE TITLE
nginx proxy_pass port should be environment driven for dynamic allocation

### ISSUE THREAD

**Issue by tomkp75** [shoonoise/cabot-docker#17]
Hello,

Marathon allows for dynamic port allocation.
I found it useful to use envplate (https://github.com/kreuzwerker/envplate) for setting the proxy_pass port in nginx.conf from an environment variable.

Thanks,

Tom

**Comment by shoonoise** [comment]
@tomkp75 this project basically for bootstrap full Cabot env. 
My point - there are no reasons to change upstream port so far as it's docker-to-docker communication.
