### ISSUE TITLE
Invalid service name "celery_broker"

### ISSUE THREAD

**Issue by mabushey** [shoonoise/cabot-docker#21]
I'm guessing the docs are missing doing a git clone of the repo, and cd into the dir ebfore running 'docker-compose up -d`. 

```
root@server:~/source/cabot-docker# docker-compose up -d
Invalid service name "celery_broker" - only [a-zA-Z0-9] are allowed
```

**Comment by bcubk** [comment]
Hi @mabushey, please check the Version of your Docker Compose. Since Version 1.4.0 it is allowed to use dots, dashes and underscores. (see https://github.com/docker/compose/releases/tag/1.4.0)

**Comment by shoonoise** [comment]
@mabushey as @bcubk says you may just update Docker Compose or rename dir to `cabotDocker` or something like that.
