### ISSUE TITLE
Use official Postgres image instead of orchardup/postgresql

### ISSUE THREAD

**Issue by bufke** [shoonoise/cabot-docker#22]
orchardup/postgresql is from the fig days - it's deprecated. Should be able to just replace it.

See this more up to date doc https://docs.docker.com/compose/django/

**Comment by shoonoise** [comment]
Thanks!

**Comment by gastontejia** [comment]
I do find an image available for postgres, but the image name its different

https://hub.docker.com/_/postgres/

using image:posgresql does not work on my setup, using image:postgres does succedd doing the pull.

But somehow it does not create the right roles/pass on the database, so i got an "role docker does not exist" when starting the UI. 

I am quite new using docker, so please excuse any conceptual mistake.

**Comment by bufke** [comment]
Yeah it should be 

```
db:
  image: postgres
```
