### ISSUE TITLE
Cabot app throws error due to mismatch in database password environment variable

### ISSUE THREAD

**Issue by skstronghold** [shoonoise/cabot-docker#26]
Cobot doesn't work as expected as there is a mismatch in environment variable specified in Dockerfile(`DB_PASSWORD`) and run.sh(`DB_PASS`)

Both variables should be same. Renaming environment variable to `DB_PASS` in Dockerfile fixes this issue.

**Comment by alanevans** [comment]
I had this issue also.  And the fix described above fixed it.  Note that you have to explicitly docker-compose build to rebuild after making the change.
