### ISSUE TITLE
Question: Dependency on Docker Engine 1.9.0 

### ISSUE THREAD

**Issue by IVBakker** [shoonoise/cabot-docker#35]
Hi,

When trying to install using docker-compose it throws the following error:
```ERROR: The engine version is lesser than the minimum required by compose. Your current project requires a Docker Engine of version 1.9.0 or superior.```

I couldn't find in ```docker-compose.yml``` any reason of that.
Is this really a hard constrain?

**Comment by shoonoise** [comment]
@IVBakker hi
docker-compose depends on docker-engine at self, it's not a this project dependency.
