### ISSUE TITLE
Can't integrate cabot slack alert plugin

### ISSUE THREAD

**Issue by erez-rabih** [shoonoise/cabot-docker#38]
Hi I am trying to work with the slack plugin with no success

I tried to add 
`ENV CABOT_PLUGINS_ENABLED cabot_alert_hipchat,cabot_alert_twilio,cabot_alert_email,cabot_alert_slack==0.6`
after line 23 in the Dockerfile
but the slack alert still doesn't show on the list of available handlers.

Any solution to this?

**Comment by shoonoise** [comment]
Hi @erez-rabih 
Show you `dockerfile` please.

**Comment by erez-rabih** [comment]
Hi @shoonoise it has been long ago when I've tried to integrate slack alert plugin with cabot-docker installation.
I found a workaround in which I publish to an email address slack listens on so alerts arrive to slack.
The Dockerfile I used is the same one that is on this repository just added the stated line after line 23 in the Dockerfile.

**Comment by shoonoise** [comment]
@erez-rabih seems like it's the plugin related problem
sorry, I can't fix it
