### ISSUE TITLE
ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by elcolie** [shoonoise/cabot-docker#39]
Hi 
I have installed everything in your requirements already.
My spec are as belows
OSX: 10.11.6
I use latest docker version

```
(uih_portal) Sarits-MacBook-Air-2:cabot-docker el$ docker --version
Docker version 1.12.0, build 8eab29e
(uih_portal) Sarits-MacBook-Air-2:cabot-docker el$ docker-compose --version
docker-compose version 1.8.0, build f3628c7
```

```
$ git clone https://github.com/shoonoise/cabot-docker.git && cd cabot-docker
Cloning into 'cabot-docker'...
remote: Counting objects: 178, done.
remote: Total 178 (delta 0), reused 0 (delta 0), pack-reused 178
Receiving objects: 100% (178/178), 31.81 KiB | 0 bytes/s, done.
Resolving deltas: 100% (72/72), done.
Checking connectivity... done.
(uih_portal) Sarits-MacBook-Air-2:cabot-docker el$ pwd
/Users/el/Code/uih-portal/portal/cabot-docker
(uih_portal) Sarits-MacBook-Air-2:cabot-docker el$ ls
Cabot           LICENSE.md      README.md       cabot_env       docker-compose.yml
(uih_portal) Sarits-MacBook-Air-2:cabot-docker el$ docker-compose up -d
cabotdocker_celerybroker_1 is up-to-date
Starting cabotdocker_db_1
cabotdocker_smtp_1 is up-to-date

ERROR: for db  Cannot start service db: Mounts denied:
The path /var/lib/cabotdb
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERROR: Encountered errors while bringing up the project.
```

**Comment by sjwoodr** [comment]
You'd need to explicitly share this directory in your Docker for Mac preferences.  Click the whale in the top bar, Preferences..., and then click into 'File Sharing' to specify the /var/lib/cabotdb directory. 

I haven't tried this for cabot, but I've done this before for other things which require host mounts while running in OS X.

**Comment by edwardmp** [comment]
On other platforms (Synology NAS => Linux) I needed to manually create /var/lib/cabotdb

**Comment by shoonoise** [comment]
@elcolie 
It's docker for mac specific issue. Just try to follow error message instructions 😃 

For example, you may to change mount point to `/User/%username%/tmp/cabotdb:/var/lib/postgresql`

But you have to ensure you have the dir (`/User/%username%/tmp/cabotdb`) on your mac and the path in your docker preference (`Docker -> Preferences... -> File Sharing`)

**Comment by vassyz** [comment]
I got it working by creating `/Users/%username%/tmp/cabotdb`, adding it to Docker File Sharing, and also adding the path to `/Users/%username%/%project%/cabot-docker/Cabot`. I had to remove the `/Users` directory because it was overlapping.
