### ISSUE TITLE
Accessing web after deploy

### ISSUE THREAD

**Issue by romankor** [shoonoise/cabot-docker#8]
Hi 
Very new to docker , sorry if the questions are stupid
I have deployed cabot through docker to one of my ec2 vms . It see that there is no gunicorn process running for the cabot web service ? 
But I see all the celery , postres , redis processes and some docker proxies 
```
docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8000 -container-ip 172.17.0.5 -container-port 8000
```
I guess thats the process that proxies the localhost:8000 to the container that runs the web server , but there is not web server

**Comment by barthoda** [comment]
This might not be helpful, but this set of docker containers worked for me straight away.
